name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: LaTeX compilation
        uses: dante-ev/latex-action@v0.2.0
        with:
          # The root LaTeX file to be compiled
          root_file: main.tex

